import Head from 'next/head'
import Image from 'next/image'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'

export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log('hello');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Coffeeee Connoisseur</h1> */}
        <Banner 
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
          bannerText="Discover your local coffee shop!"
          />
          <div className ={styles.heroImage}>
            <Image src="/static/hero-image.png" width={700} height={400}/>
            </div>
        <Card/>
      </main>

    </div>
  )
}
